slugs = ["cryptowomen"]
[options]
buy_sell_delay = [40_000, 80_000]
between_cycle_delay = [40_000, 80_000]
nft_update_interval = 500_000
   
[[accounts]]
pk = "****************"
impersonate = "chrome120"
[accounts.proxy]
kind = "Socks5"
addr = "192.168.0.1"
port = 1234
creds = ["login", "password"]

[[accounts]]
pk = "****************"
impersonate = "chrome119"

[accounts.proxy]
kind = "Socks5"
addr = "192.168.0.1"
port = 1234
creds = ["login", "password"]
