# Terms of Service

## Introduction
These Terms of Service (“Terms”) govern your use of the services and software provided by Seller. By accessing or using our services and software, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please refrain from using our services and software.

### 1. No Responsibility for Losses
1.1. **Disclaimer**: Seller does not assume any responsibility or liability for any losses, damages, or adverse consequences resulting from the use of our products or services. Users are solely responsible for their actions and decisions while using our offerings.

1.2. **No Warranty**: Our products and services are provided “as is” and without any warranties or guarantees. We do not guarantee the accuracy, reliability, or effectiveness of our offerings. Users should exercise caution and perform their own due diligence.

### 2. Anti-Sybil Mechanisms
2.1. **Detection Risks**: Seller acknowledges that anti-sybil mechanisms may detect and prevent certain activities. However, we do not guarantee that our users will remain undetected. Users should be aware of the risks associated with such mechanisms.

2.2. **User Responsibility**: Users are responsible for understanding and complying with any anti-sybil measures implemented. Seller shall not be liable for any consequences arising from detection by these mechanisms.

### 3. Software Workability
3.1. **Post-Sale Software Performance**: Seller does not guarantee the continued workability or functionality of the software after it has been sold. Users should assess the software’s suitability for their needs before purchase.

3.2. **Updates and Maintenance**: While we strive to maintain and improve our software, there may be instances where updates or maintenance affect its performance. Users should regularly check for updates and follow any instructions provided.

3.3. **Best-effort based support**: Seller acknowledges that special updates to projects may break core mechanisms, rendering certain features non-functional. In such cases, no patch can be guaranteed. Users should be aware of this limitation.

### 4. Refunds
4.1. **Software Refunds**: Seller under no circumstances provides refunds for purchased software. All sales are final.

4.2. **Service Refunds**: In special circumstances, Seller may provide refunds for bought services on a pro-rata basis. Such cases will be evaluated on an individual basis, but refunds are not guaranteed.

### 5. Buyer Acceptance
5.1. **Acceptance at Point** of Sale: By purchasing our products or services, the buyer explicitly accepts these Terms of Service. The act of buying signifies agreement to all terms outlined herein.

### 6. Limitation of Liability
6.1. **Exclusion of Damages**: In no event shall Seller be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of our products or services.

6.2. **Maximum Liability**: To the maximum extent permitted by applicable law, Seller’s total liability shall not exceed the amount paid by the user for the specific product or service.

### 7. User Conduct
7.1. **Acceptable Use**: Users must use our services and software in a lawful and respectful manner. This includes refraining from engaging in any activity that violates applicable laws, regulations, or the rights of others.

7.2. **Prohibited Actions**: Users shall not:

Harass, threaten, or intimidate other users or our staff.
Upload, transmit, or distribute any content that is illegal, harmful, defamatory, or infringes upon intellectual property rights.
Attempt to circumvent security measures, manipulate our systems, or disrupt the experience for other users.
Engage in fraudulent or deceptive practices related to our offerings. </br>

7.3. **Reporting Violations**: If users encounter any violations of these conduct guidelines, they should promptly report them to us for investigation.

### 8. Acceptance
By using our services or software, you acknowledge that you have read, understood, and agreed to these Terms. If you disagree with any part of these Terms, please refrain from using our offerings.
